[program:ragf_server]
directory=/ragf
command=/usr/local/bin/python -m uvicorn backend.main:app --host 0.0.0.0 --port 8001 --workers 1
user=root
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/var/log/ragf/ragf_server.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=5