[program:ragf_celery_knowhere_worker]
directory=/ragf
command=/usr/local/bin/celery -A backend.src.app.task.celery:celery_app worker -P gevent -c 1000 -Q knowhere --loglevel=INFO
user=root
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/var/log/ragf/ragf_celery_knowhere_worker.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=5
