/** @type {import('tailwindcss').Config} */

const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          1: 'rgb(var(--primary-1) / <alpha-value>)',
          2: 'rgb(var(--primary-2) / <alpha-value>)',
          3: 'rgb(var(--primary-3) / <alpha-value>)',
          4: 'rgb(var(--primary-4) / <alpha-value>)',
          5: 'rgb(var(--primary-5) / <alpha-value>)',
          6: 'rgb(var(--primary-6) / <alpha-value>)',
          7: 'rgb(var(--primary-7) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        success: {
          1: 'rgb(var(--success-1) / <alpha-value>)',
          2: 'rgb(var(--success-2) / <alpha-value>)',
          3: 'rgb(var(--success-3) / <alpha-value>)',
          4: 'rgb(var(--success-4) / <alpha-value>)',
          5: 'rgb(var(--success-5) / <alpha-value>)',
          6: 'rgb(var(--success-6) / <alpha-value>)',
          7: 'rgb(var(--success-7) / <alpha-value>)',
        },
        warning: {
          1: 'rgb(var(--warning-1) / <alpha-value>)',
          2: 'rgb(var(--warning-2) / <alpha-value>)',
          3: 'rgb(var(--warning-3) / <alpha-value>)',
          4: 'rgb(var(--warning-4) / <alpha-value>)',
          5: 'rgb(var(--warning-5) / <alpha-value>)',
          6: 'rgb(var(--warning-6) / <alpha-value>)',
          7: 'rgb(var(--warning-7) / <alpha-value>)',
        },
        danger: {
          1: 'rgb(var(--danger-1) / <alpha-value>)',
          2: 'rgb(var(--danger-2) / <alpha-value>)',
          3: 'rgb(var(--danger-3) / <alpha-value>)',
          4: 'rgb(var(--danger-4) / <alpha-value>)',
          5: 'rgb(var(--danger-5) / <alpha-value>)',
          6: 'rgb(var(--danger-6) / <alpha-value>)',
          7: 'rgb(var(--danger-7) / <alpha-value>)',
        },
        link: {
          1: 'rgb(var(--link-1) / <alpha-value>)',
          2: 'rgb(var(--link-2) / <alpha-value>)',
          3: 'rgb(var(--link-3) / <alpha-value>)',
          4: 'rgb(var(--link-4) / <alpha-value>)',
          5: 'rgb(var(--link-5) / <alpha-value>)',
          6: 'rgb(var(--link-6) / <alpha-value>)',
          7: 'rgb(var(--link-7) / <alpha-value>)',
        },
        data: {
          1: 'rgb(var(--data-1) / <alpha-value>)',
          2: 'rgb(var(--data-2) / <alpha-value>)',
          3: 'rgb(var(--data-3) / <alpha-value>)',
          4: 'rgb(var(--data-4) / <alpha-value>)',
          5: 'rgb(var(--data-5) / <alpha-value>)',
          6: 'rgb(var(--data-6) / <alpha-value>)',
          7: 'rgb(var(--data-7) / <alpha-value>)',
          8: 'rgb(var(--data-8) / <alpha-value>)',
          9: 'rgb(var(--data-9) / <alpha-value>)',
          10: 'rgb(var(--data-10) / <alpha-value>)',
          11: 'rgb(var(--data-11) / <alpha-value>)',
          12: 'rgb(var(--data-12) / <alpha-value>)',
          13: 'rgb(var(--data-13) / <alpha-value>)',
          14: 'rgb(var(--data-14) / <alpha-value>)',
          15: 'rgb(var(--data-15) / <alpha-value>)',
          16: 'rgb(var(--data-16) / <alpha-value>)',
          17: 'rgb(var(--data-17) / <alpha-value>)',
          18: 'rgb(var(--data-18) / <alpha-value>)',
          19: 'rgb(var(--data-19) / <alpha-value>)',
          20: 'rgb(var(--data-20) / <alpha-value>)',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        'color-bg': {
          1: 'rgb(var(--color-bg-1) / <alpha-value>)',
          2: 'rgb(var(--color-bg-2) / <alpha-value>)',
          3: 'rgb(var(--color-bg-3) / <alpha-value>)',
          4: 'rgb(var(--color-bg-4) / <alpha-value>)',
          5: 'rgb(var(--color-bg-5) / <alpha-value>)',
          white: 'rgb(var(--color-bg-white) / <alpha-value>)',
        },
        'color-border': {
          1: 'rgb(var(--color-border-1) / <alpha-value>)',
          2: 'rgb(var(--color-border-2) / <alpha-value>)',
          3: 'rgb(var(--color-border-3) / <alpha-value>)',
          4: 'rgb(var(--color-border-4) / <alpha-value>)',
        },
        'color-fill': {
          1: 'rgb(var(--color-fill-1) / <alpha-value>)',
          2: 'rgb(var(--color-fill-2) / <alpha-value>)',
          3: 'rgb(var(--color-fill-3) / <alpha-value>)',
          4: 'rgb(var(--color-fill-4) / <alpha-value>)',
        },
        'color-text': {
          1: 'rgb(var(--color-text-1) / <alpha-value>)',
          2: 'rgb(var(--color-text-2) / <alpha-value>)',
          3: 'rgb(var(--color-text-3) / <alpha-value>)',
          4: 'rgb(var(--color-text-4) / <alpha-value>)',
        },
        'color-white': 'rgb(var(--color-white) / <alpha-value>)',
        'color-black': 'rgb(var(--color-black) / <alpha-value>)',
      },
      fontSize: {
        'body-3': 'var(--font-size-body-3)',
        'body-2': 'var(--font-size-body-2)',
        'body-1': 'var(--font-size-body-1)',
        caption: 'var(--font-size-caption)',
        'title-1': 'var(--font-size-title-1)',
        'title-2': 'var(--font-size-title-2)',
        'title-3': 'var(--font-size-title-3)',
        'display-1': 'var(--font-size-display-1)',
        'display-2': 'var(--font-size-display-2)',
        'display-3': 'var(--font-size-display-3)',
      },
      fontWeight: {
        'weight-100': 'var(--font-weight-100)',
        'weight-200': 'var(--font-weight-200)',
        'weight-300': 'var(--font-weight-300)',
        'weight-400': 'var(--font-weight-400)',
        'weight-500': 'var(--font-weight-500)',
        'weight-600': 'var(--font-weight-600)',
        'weight-700': 'var(--font-weight-700)',
        'weight-800': 'var(--font-weight-800)',
        'weight-900': 'var(--font-weight-900)',
      },
      spacing: {
        'size-1': 'var(--size-1)',
        'size-2': 'var(--size-2)',
        'size-3': 'var(--size-3)',
        'size-4': 'var(--size-4)',
        'size-5': 'var(--size-5)',
        'size-6': 'var(--size-6)',
        'size-7': 'var(--size-7)',
        'size-8': 'var(--size-8)',
        'size-9': 'var(--size-9)',
        'size-10': 'var(--size-10)',
        'size-11': 'var(--size-11)',
        'size-12': 'var(--size-12)',
        'size-13': 'var(--size-13)',
        'size-14': 'var(--size-14)',
        'size-15': 'var(--size-15)',
        'size-16': 'var(--size-16)',
        'size-17': 'var(--size-17)',
        'size-18': 'var(--size-18)',
        'size-19': 'var(--size-19)',
        'size-20': 'var(--size-20)',
        'size-21': 'var(--size-21)',
        'size-22': 'var(--size-22)',
        'size-23': 'var(--size-23)',
        'size-24': 'var(--size-24)',
        'size-25': 'var(--size-25)',
        'size-26': 'var(--size-26)',
        'size-27': 'var(--size-27)',
        'size-28': 'var(--size-28)',
        'size-29': 'var(--size-29)',
        'size-30': 'var(--size-30)',
        'size-31': 'var(--size-31)',
        'size-32': 'var(--size-32)',
        'size-33': 'var(--size-33)',
        'size-34': 'var(--size-34)',
        'size-35': 'var(--size-35)',
        'size-36': 'var(--size-36)',
        'size-37': 'var(--size-37)',
        'size-38': 'var(--size-38)',
        'size-39': 'var(--size-39)',
        'size-40': 'var(--size-40)',
        'size-41': 'var(--size-41)',
        'size-42': 'var(--size-42)',
        'size-43': 'var(--size-43)',
        'size-44': 'var(--size-44)',
        'size-45': 'var(--size-45)',
        'size-46': 'var(--size-46)',
        'size-47': 'var(--size-47)',
        'size-48': 'var(--size-48)',
        'size-49': 'var(--size-49)',
        'size-50': 'var(--size-50)',
      },
      borderRadius: {
        sm: 'var(--border-radius-small)',
        md: 'var(--border-radius-medium)',
        lg: 'var(--border-radius-large)',
        small: 'var(--border-radius-small)',
        medium: 'var(--border-radius-medium)',
        large: 'var(--border-radius-large)',
        circle: 'var(--border-radius-circle)',
      },
      borderWidth: {
        1: 'var(--border-1)',
        3: 'var(--border-3)',
      },
      boxShadow: {
        special: 'var(--shadow-special)',
        '1-center': 'var(--shadow-1-center)',
        '2-center': 'var(--shadow-2-center)',
        '3-center': 'var(--shadow-3-center)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
};
